/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ScalesRouteImport } from './routes/scales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as NurseRouteImport } from './routes/nurse'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MeRouteImport } from './routes/me'
import { Route as EducationRouteImport } from './routes/education'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NurseIndexRouteImport } from './routes/nurse.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as ScalesIdRouteImport } from './routes/scales_.$id'
import { Route as ReportsIdRouteImport } from './routes/reports_.$id'
import { Route as QuestionnaireSelfRouteImport } from './routes/questionnaire_.self'
import { Route as QuestionnaireResultRouteImport } from './routes/questionnaire_.result'
import { Route as QuestionnaireLifeRouteImport } from './routes/questionnaire_.life'
import { Route as NursePatientsRouteImport } from './routes/nurse.patients'
import { Route as NurseMeRouteImport } from './routes/nurse.me'
import { Route as NurseFollowupRouteImport } from './routes/nurse.followup'
import { Route as NurseEducationRouteImport } from './routes/nurse.education'
import { Route as NurseChatRouteImport } from './routes/nurse.chat'
import { Route as EducationIdRouteImport } from './routes/education.$id'
import { Route as DoctorStatsRouteImport } from './routes/doctor.stats'
import { Route as DoctorMeRouteImport } from './routes/doctor.me'
import { Route as DoctorPlansIndexRouteImport } from './routes/doctor.plans.index'
import { Route as DoctorPatientsIndexRouteImport } from './routes/doctor.patients.index'
import { Route as DoctorChatIndexRouteImport } from './routes/doctor.chat.index'
import { Route as NursePatientsIdRouteImport } from './routes/nurse.patients.$id'
import { Route as DoctorPlansIdRouteImport } from './routes/doctor.plans.$id'
import { Route as DoctorPatientsIdRouteImport } from './routes/doctor.patients.$id'
import { Route as DoctorChatIdRouteImport } from './routes/doctor.chat.$id'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ScalesRoute = ScalesRouteImport.update({
  id: '/scales',
  path: '/scales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseRoute = NurseRouteImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseIndexRoute = NurseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NurseRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const ScalesIdRoute = ScalesIdRouteImport.update({
  id: '/scales_/$id',
  path: '/scales/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports_/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireSelfRoute = QuestionnaireSelfRouteImport.update({
  id: '/questionnaire_/self',
  path: '/questionnaire/self',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireResultRoute = QuestionnaireResultRouteImport.update({
  id: '/questionnaire_/result',
  path: '/questionnaire/result',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireLifeRoute = QuestionnaireLifeRouteImport.update({
  id: '/questionnaire_/life',
  path: '/questionnaire/life',
  getParentRoute: () => rootRouteImport,
} as any)
const NursePatientsRoute = NursePatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => NurseRoute,
} as any)
const NurseMeRoute = NurseMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => NurseRoute,
} as any)
const NurseFollowupRoute = NurseFollowupRouteImport.update({
  id: '/followup',
  path: '/followup',
  getParentRoute: () => NurseRoute,
} as any)
const NurseEducationRoute = NurseEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => NurseRoute,
} as any)
const NurseChatRoute = NurseChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => NurseRoute,
} as any)
const EducationIdRoute = EducationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EducationRoute,
} as any)
const DoctorStatsRoute = DoctorStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorMeRoute = DoctorMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPlansIndexRoute = DoctorPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsIndexRoute = DoctorPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorChatIndexRoute = DoctorChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => DoctorRoute,
} as any)
const NursePatientsIdRoute = NursePatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NursePatientsRoute,
} as any)
const DoctorPlansIdRoute = DoctorPlansIdRouteImport.update({
  id: '/plans/$id',
  path: '/plans/$id',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsIdRoute = DoctorPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorChatIdRoute = DoctorChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => DoctorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/community': typeof CommunityRoute
  '/consult': typeof ConsultRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/education': typeof EducationRouteWithChildren
  '/me': typeof MeRoute
  '/messages': typeof MessagesRoute
  '/nurse': typeof NurseRouteWithChildren
  '/patient': typeof PatientRoute
  '/plan': typeof PlanRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/records': typeof RecordsRoute
  '/reports': typeof ReportsRoute
  '/scales': typeof ScalesRoute
  '/tasks': typeof TasksRoute
  '/doctor/me': typeof DoctorMeRoute
  '/doctor/stats': typeof DoctorStatsRoute
  '/education/$id': typeof EducationIdRoute
  '/nurse/chat': typeof NurseChatRoute
  '/nurse/education': typeof NurseEducationRoute
  '/nurse/followup': typeof NurseFollowupRoute
  '/nurse/me': typeof NurseMeRoute
  '/nurse/patients': typeof NursePatientsRouteWithChildren
  '/questionnaire/life': typeof QuestionnaireLifeRoute
  '/questionnaire/result': typeof QuestionnaireResultRoute
  '/questionnaire/self': typeof QuestionnaireSelfRoute
  '/reports/$id': typeof ReportsIdRoute
  '/scales/$id': typeof ScalesIdRoute
  '/doctor/': typeof DoctorIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/doctor/chat/$id': typeof DoctorChatIdRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
  '/doctor/plans/$id': typeof DoctorPlansIdRoute
  '/nurse/patients/$id': typeof NursePatientsIdRoute
  '/doctor/chat/': typeof DoctorChatIndexRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
  '/doctor/plans/': typeof DoctorPlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/community': typeof CommunityRoute
  '/consult': typeof ConsultRoute
  '/education': typeof EducationRouteWithChildren
  '/me': typeof MeRoute
  '/messages': typeof MessagesRoute
  '/patient': typeof PatientRoute
  '/plan': typeof PlanRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/records': typeof RecordsRoute
  '/reports': typeof ReportsRoute
  '/scales': typeof ScalesRoute
  '/tasks': typeof TasksRoute
  '/doctor/me': typeof DoctorMeRoute
  '/doctor/stats': typeof DoctorStatsRoute
  '/education/$id': typeof EducationIdRoute
  '/nurse/chat': typeof NurseChatRoute
  '/nurse/education': typeof NurseEducationRoute
  '/nurse/followup': typeof NurseFollowupRoute
  '/nurse/me': typeof NurseMeRoute
  '/nurse/patients': typeof NursePatientsRouteWithChildren
  '/questionnaire/life': typeof QuestionnaireLifeRoute
  '/questionnaire/result': typeof QuestionnaireResultRoute
  '/questionnaire/self': typeof QuestionnaireSelfRoute
  '/reports/$id': typeof ReportsIdRoute
  '/scales/$id': typeof ScalesIdRoute
  '/doctor': typeof DoctorIndexRoute
  '/nurse': typeof NurseIndexRoute
  '/doctor/chat/$id': typeof DoctorChatIdRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
  '/doctor/plans/$id': typeof DoctorPlansIdRoute
  '/nurse/patients/$id': typeof NursePatientsIdRoute
  '/doctor/chat': typeof DoctorChatIndexRoute
  '/doctor/patients': typeof DoctorPatientsIndexRoute
  '/doctor/plans': typeof DoctorPlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/community': typeof CommunityRoute
  '/consult': typeof ConsultRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/education': typeof EducationRouteWithChildren
  '/me': typeof MeRoute
  '/messages': typeof MessagesRoute
  '/nurse': typeof NurseRouteWithChildren
  '/patient': typeof PatientRoute
  '/plan': typeof PlanRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/records': typeof RecordsRoute
  '/reports': typeof ReportsRoute
  '/scales': typeof ScalesRoute
  '/tasks': typeof TasksRoute
  '/doctor/me': typeof DoctorMeRoute
  '/doctor/stats': typeof DoctorStatsRoute
  '/education/$id': typeof EducationIdRoute
  '/nurse/chat': typeof NurseChatRoute
  '/nurse/education': typeof NurseEducationRoute
  '/nurse/followup': typeof NurseFollowupRoute
  '/nurse/me': typeof NurseMeRoute
  '/nurse/patients': typeof NursePatientsRouteWithChildren
  '/questionnaire_/life': typeof QuestionnaireLifeRoute
  '/questionnaire_/result': typeof QuestionnaireResultRoute
  '/questionnaire_/self': typeof QuestionnaireSelfRoute
  '/reports_/$id': typeof ReportsIdRoute
  '/scales_/$id': typeof ScalesIdRoute
  '/doctor/': typeof DoctorIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/doctor/chat/$id': typeof DoctorChatIdRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
  '/doctor/plans/$id': typeof DoctorPlansIdRoute
  '/nurse/patients/$id': typeof NursePatientsIdRoute
  '/doctor/chat/': typeof DoctorChatIndexRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
  '/doctor/plans/': typeof DoctorPlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/community'
    | '/consult'
    | '/doctor'
    | '/education'
    | '/me'
    | '/messages'
    | '/nurse'
    | '/patient'
    | '/plan'
    | '/questionnaire'
    | '/records'
    | '/reports'
    | '/scales'
    | '/tasks'
    | '/doctor/me'
    | '/doctor/stats'
    | '/education/$id'
    | '/nurse/chat'
    | '/nurse/education'
    | '/nurse/followup'
    | '/nurse/me'
    | '/nurse/patients'
    | '/questionnaire/life'
    | '/questionnaire/result'
    | '/questionnaire/self'
    | '/reports/$id'
    | '/scales/$id'
    | '/doctor/'
    | '/nurse/'
    | '/doctor/chat/$id'
    | '/doctor/patients/$id'
    | '/doctor/plans/$id'
    | '/nurse/patients/$id'
    | '/doctor/chat/'
    | '/doctor/patients/'
    | '/doctor/plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/community'
    | '/consult'
    | '/education'
    | '/me'
    | '/messages'
    | '/patient'
    | '/plan'
    | '/questionnaire'
    | '/records'
    | '/reports'
    | '/scales'
    | '/tasks'
    | '/doctor/me'
    | '/doctor/stats'
    | '/education/$id'
    | '/nurse/chat'
    | '/nurse/education'
    | '/nurse/followup'
    | '/nurse/me'
    | '/nurse/patients'
    | '/questionnaire/life'
    | '/questionnaire/result'
    | '/questionnaire/self'
    | '/reports/$id'
    | '/scales/$id'
    | '/doctor'
    | '/nurse'
    | '/doctor/chat/$id'
    | '/doctor/patients/$id'
    | '/doctor/plans/$id'
    | '/nurse/patients/$id'
    | '/doctor/chat'
    | '/doctor/patients'
    | '/doctor/plans'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/community'
    | '/consult'
    | '/doctor'
    | '/education'
    | '/me'
    | '/messages'
    | '/nurse'
    | '/patient'
    | '/plan'
    | '/questionnaire'
    | '/records'
    | '/reports'
    | '/scales'
    | '/tasks'
    | '/doctor/me'
    | '/doctor/stats'
    | '/education/$id'
    | '/nurse/chat'
    | '/nurse/education'
    | '/nurse/followup'
    | '/nurse/me'
    | '/nurse/patients'
    | '/questionnaire_/life'
    | '/questionnaire_/result'
    | '/questionnaire_/self'
    | '/reports_/$id'
    | '/scales_/$id'
    | '/doctor/'
    | '/nurse/'
    | '/doctor/chat/$id'
    | '/doctor/patients/$id'
    | '/doctor/plans/$id'
    | '/nurse/patients/$id'
    | '/doctor/chat/'
    | '/doctor/patients/'
    | '/doctor/plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  CommunityRoute: typeof CommunityRoute
  ConsultRoute: typeof ConsultRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  EducationRoute: typeof EducationRouteWithChildren
  MeRoute: typeof MeRoute
  MessagesRoute: typeof MessagesRoute
  NurseRoute: typeof NurseRouteWithChildren
  PatientRoute: typeof PatientRoute
  PlanRoute: typeof PlanRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  RecordsRoute: typeof RecordsRoute
  ReportsRoute: typeof ReportsRoute
  ScalesRoute: typeof ScalesRoute
  TasksRoute: typeof TasksRoute
  QuestionnaireLifeRoute: typeof QuestionnaireLifeRoute
  QuestionnaireResultRoute: typeof QuestionnaireResultRoute
  QuestionnaireSelfRoute: typeof QuestionnaireSelfRoute
  ReportsIdRoute: typeof ReportsIdRoute
  ScalesIdRoute: typeof ScalesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scales': {
      id: '/scales'
      path: '/scales'
      fullPath: '/scales'
      preLoaderRoute: typeof ScalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse': {
      id: '/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse/': {
      id: '/nurse/'
      path: '/'
      fullPath: '/nurse/'
      preLoaderRoute: typeof NurseIndexRouteImport
      parentRoute: typeof NurseRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/scales_/$id': {
      id: '/scales_/$id'
      path: '/scales/$id'
      fullPath: '/scales/$id'
      preLoaderRoute: typeof ScalesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports_/$id': {
      id: '/reports_/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire_/self': {
      id: '/questionnaire_/self'
      path: '/questionnaire/self'
      fullPath: '/questionnaire/self'
      preLoaderRoute: typeof QuestionnaireSelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire_/result': {
      id: '/questionnaire_/result'
      path: '/questionnaire/result'
      fullPath: '/questionnaire/result'
      preLoaderRoute: typeof QuestionnaireResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire_/life': {
      id: '/questionnaire_/life'
      path: '/questionnaire/life'
      fullPath: '/questionnaire/life'
      preLoaderRoute: typeof QuestionnaireLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse/patients': {
      id: '/nurse/patients'
      path: '/patients'
      fullPath: '/nurse/patients'
      preLoaderRoute: typeof NursePatientsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/me': {
      id: '/nurse/me'
      path: '/me'
      fullPath: '/nurse/me'
      preLoaderRoute: typeof NurseMeRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/followup': {
      id: '/nurse/followup'
      path: '/followup'
      fullPath: '/nurse/followup'
      preLoaderRoute: typeof NurseFollowupRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/education': {
      id: '/nurse/education'
      path: '/education'
      fullPath: '/nurse/education'
      preLoaderRoute: typeof NurseEducationRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/chat': {
      id: '/nurse/chat'
      path: '/chat'
      fullPath: '/nurse/chat'
      preLoaderRoute: typeof NurseChatRouteImport
      parentRoute: typeof NurseRoute
    }
    '/education/$id': {
      id: '/education/$id'
      path: '/$id'
      fullPath: '/education/$id'
      preLoaderRoute: typeof EducationIdRouteImport
      parentRoute: typeof EducationRoute
    }
    '/doctor/stats': {
      id: '/doctor/stats'
      path: '/stats'
      fullPath: '/doctor/stats'
      preLoaderRoute: typeof DoctorStatsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/me': {
      id: '/doctor/me'
      path: '/me'
      fullPath: '/doctor/me'
      preLoaderRoute: typeof DoctorMeRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/plans/': {
      id: '/doctor/plans/'
      path: '/plans'
      fullPath: '/doctor/plans/'
      preLoaderRoute: typeof DoctorPlansIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients/': {
      id: '/doctor/patients/'
      path: '/patients'
      fullPath: '/doctor/patients/'
      preLoaderRoute: typeof DoctorPatientsIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/chat/': {
      id: '/doctor/chat/'
      path: '/chat'
      fullPath: '/doctor/chat/'
      preLoaderRoute: typeof DoctorChatIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/nurse/patients/$id': {
      id: '/nurse/patients/$id'
      path: '/$id'
      fullPath: '/nurse/patients/$id'
      preLoaderRoute: typeof NursePatientsIdRouteImport
      parentRoute: typeof NursePatientsRoute
    }
    '/doctor/plans/$id': {
      id: '/doctor/plans/$id'
      path: '/plans/$id'
      fullPath: '/doctor/plans/$id'
      preLoaderRoute: typeof DoctorPlansIdRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients/$id': {
      id: '/doctor/patients/$id'
      path: '/patients/$id'
      fullPath: '/doctor/patients/$id'
      preLoaderRoute: typeof DoctorPatientsIdRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/chat/$id': {
      id: '/doctor/chat/$id'
      path: '/chat/$id'
      fullPath: '/doctor/chat/$id'
      preLoaderRoute: typeof DoctorChatIdRouteImport
      parentRoute: typeof DoctorRoute
    }
  }
}

interface DoctorRouteChildren {
  DoctorMeRoute: typeof DoctorMeRoute
  DoctorStatsRoute: typeof DoctorStatsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorChatIdRoute: typeof DoctorChatIdRoute
  DoctorPatientsIdRoute: typeof DoctorPatientsIdRoute
  DoctorPlansIdRoute: typeof DoctorPlansIdRoute
  DoctorChatIndexRoute: typeof DoctorChatIndexRoute
  DoctorPatientsIndexRoute: typeof DoctorPatientsIndexRoute
  DoctorPlansIndexRoute: typeof DoctorPlansIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorMeRoute: DoctorMeRoute,
  DoctorStatsRoute: DoctorStatsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorChatIdRoute: DoctorChatIdRoute,
  DoctorPatientsIdRoute: DoctorPatientsIdRoute,
  DoctorPlansIdRoute: DoctorPlansIdRoute,
  DoctorChatIndexRoute: DoctorChatIndexRoute,
  DoctorPatientsIndexRoute: DoctorPatientsIndexRoute,
  DoctorPlansIndexRoute: DoctorPlansIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface EducationRouteChildren {
  EducationIdRoute: typeof EducationIdRoute
}

const EducationRouteChildren: EducationRouteChildren = {
  EducationIdRoute: EducationIdRoute,
}

const EducationRouteWithChildren = EducationRoute._addFileChildren(
  EducationRouteChildren,
)

interface NursePatientsRouteChildren {
  NursePatientsIdRoute: typeof NursePatientsIdRoute
}

const NursePatientsRouteChildren: NursePatientsRouteChildren = {
  NursePatientsIdRoute: NursePatientsIdRoute,
}

const NursePatientsRouteWithChildren = NursePatientsRoute._addFileChildren(
  NursePatientsRouteChildren,
)

interface NurseRouteChildren {
  NurseChatRoute: typeof NurseChatRoute
  NurseEducationRoute: typeof NurseEducationRoute
  NurseFollowupRoute: typeof NurseFollowupRoute
  NurseMeRoute: typeof NurseMeRoute
  NursePatientsRoute: typeof NursePatientsRouteWithChildren
  NurseIndexRoute: typeof NurseIndexRoute
}

const NurseRouteChildren: NurseRouteChildren = {
  NurseChatRoute: NurseChatRoute,
  NurseEducationRoute: NurseEducationRoute,
  NurseFollowupRoute: NurseFollowupRoute,
  NurseMeRoute: NurseMeRoute,
  NursePatientsRoute: NursePatientsRouteWithChildren,
  NurseIndexRoute: NurseIndexRoute,
}

const NurseRouteWithChildren = NurseRoute._addFileChildren(NurseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  CommunityRoute: CommunityRoute,
  ConsultRoute: ConsultRoute,
  DoctorRoute: DoctorRouteWithChildren,
  EducationRoute: EducationRouteWithChildren,
  MeRoute: MeRoute,
  MessagesRoute: MessagesRoute,
  NurseRoute: NurseRouteWithChildren,
  PatientRoute: PatientRoute,
  PlanRoute: PlanRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  RecordsRoute: RecordsRoute,
  ReportsRoute: ReportsRoute,
  ScalesRoute: ScalesRoute,
  TasksRoute: TasksRoute,
  QuestionnaireLifeRoute: QuestionnaireLifeRoute,
  QuestionnaireResultRoute: QuestionnaireResultRoute,
  QuestionnaireSelfRoute: QuestionnaireSelfRoute,
  ReportsIdRoute: ReportsIdRoute,
  ScalesIdRoute: ScalesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
